name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v3
	  - name: Docker build chatservice
	    run: echo "Docker buil chatservice"
	  - name: Docker build webapp
	    run: echo "Docker buil webapp"
  CD:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Autenticar o AWS CLI
      run: echo "Configurar o aws configure"
    - name: Configuracao do Kubectl
      run: echo "Configurar o kubctl"
    - name: Deploy das Aplicações
      run: echo "Executar o camando kubctl apply"  
    
